//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstLook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bases
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public string Transmission { get; set; }
        public string Technology { get; set; }
        public string Capacity { get; set; }
        public string Altitude { get; set; }
        public string WgsLAT { get; set; }
        public string WgsLON { get; set; }
        public string EOVX { get; set; }
        public string EOVY { get; set; }
        public Nullable<int> SettlementID { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string Owner { get; set; }
        public string Connection { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string BaseID { get; set; }
    
        public virtual BuildingTypes BuildingTypes { get; set; }
        public virtual Settlements Settlements { get; set; }
    }
}
