//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstLook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bazis
    {
        public int Id { get; set; }
        public string HelyszinMegnev { get; set; }
        public string Megnevezes { get; set; }
        public int EpitmenytipusID { get; set; }
        public string WgsLAT { get; set; }
        public string WgsLON { get; set; }
    }
}
