//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstLook
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BazisokEntities4 : DbContext
    {
        public BazisokEntities4()
            : base("name=BazisokEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bases> Bases { get; set; }
        public virtual DbSet<BuildingTypes> BuildingTypes { get; set; }
        public virtual DbSet<Settlements> Settlements { get; set; }
    }
}
