//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstLook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surveys
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string Note { get; set; }
        public string SiteAddress { get; set; }
        public int Capacity { get; set; }
        public string Service { get; set; }
        public string Presales { get; set; }
        public int SurveyStateID { get; set; }
        public string BaseID { get; set; }
        public string WgsLAT { get; set; }
        public string WgsLON { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual SurveyStates SurveyStates { get; set; }
    }
}
